stintboat:
# Publish all joint states:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
# Position controllers: 
  sail_controller:
    type: position_controllers/JointPositionController
    joint: base_mast_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}
  rudder_controller:
    type: position_controllers/JointPositionController
    joint: base_pole_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}