stintboat:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  sail_controller:
    type: effort_controllers/JointPositionController
    joint: mast_sail_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rudder_controller:
    type: effort_controllers/JointPositionController
    joint: base_pole_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
